build_task:
  container:
    image: node:10-alpine
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: GULP_ENV=prod yarn build
